%------------------------------------------------------------------------------------------------------
%	This Matlab file reads the datafile generated by simulating the testbench in ModelSim:
%	The Matlab file should be saved within the same path that has the output textfile by the simulation
%...project_file > simulation	> modelsim >
%-------------------------------------------------------------------------------------------------------

clear
close all
clc

%------------------------------------------------------------------------------------------------------

load output.txt;					%	read data from the text file
index = output (:, 1);				%   copy first column of output into index 
count = output (:, 2);				%   and second column into count

plot (index, count, 'o', 'MarkerFaceColor', 'b');		% pllot count vs. index 
xlabel ('index');										% add axis labels
ylabel ('count');
title('Graphing the data obtained from the simulation file');