//Instatiante all blocks.
module MSDAP (
	
	//MSDAP INPUTS
	input wire DCLK,
	input wire SCLK,
	input wire RESET_N,
	input wire START,
	input wire FRAME,
	input wire INPUTL,
	input wire INPUTR,

	//MSDAP outputs into Testbench
	output wire INREADY,
	output wire OUTREADY,
	output wire DATAOUT_L,
	output wire DATAOUT_R
);

	//GLOBAL SIGNALS
	wire [15:0] PDATA_IN_L;
	wire [15:0] PDATA_IN_R;

	wire ALU_CLEAR;

	//RJ_MEM_L_SIGNALS
	wire RJ_CLEAR_L;
	wire [3:0] RJ_WRITE_ADDRESS_L;
	wire RJ_WRITE_EN_L;
	wire [3:0] RJ_READ_ADDRESS_L;
	wire RJ_READ_EN_L;
	wire [7:0] RJ_DATAOUT_L;

	//RJ_MEM_R_SIGNALS
	wire RJ_CLEAR_R;
	wire [3:0] RJ_WRITE_ADDRESS_R;
	wire RJ_WRITE_EN_R;
	wire [3:0] RJ_READ_ADDRESS_R;
	wire RJ_READ_EN_R;
	wire [7:0] RJ_DATAOUT_R;

	//COEFF_MEM_L_SIGNALS
	wire COEFF_CLEAR_L;
	wire [8:0] COEFF_WRITE_ADDRESS_L;
	wire COEFF_WRITE_EN_L;
	wire [8:0] COEFF_READ_ADDRESS_L;
	wire COEFF_READ_EN_L;
	wire [8:0] COEFF_DATAOUT_L;

	//COEFF_MEM_R_SIGNALS
	wire COEFF_CLEAR_R;
	wire [8:0] COEFF_WRITE_ADDRESS_R;
	wire COEFF_WRITE_EN_R;
	wire [8:0] COEFF_READ_ADDRESS_R;
	wire COEFF_READ_EN_R;
	wire [8:0] COEFF_DATAOUT_R;

	//DATA_MEM_L_SIGNALS
	wire DATA_CLEAR_L;
	wire [7:0] DATA_WRITE_ADDRESS_L;
	wire DATA_WRITE_EN_L;
	wire [7:0] DATA_READ_ADDRESS_L;
	wire DATA_READ_EN_L;
	wire [15:0] DATA_DATAOUT_L;
	wire ZERO_DETECTED_L;

	//DATA_MEM_R_SIGNALS
	wire DATA_CLEAR_R;
	wire [7:0] DATA_WRITE_ADDRESS_R;
	wire DATA_WRITE_EN_R;
	wire [7:0] DATA_READ_ADDRESS_R;
	wire DATA_READ_EN_R;
	wire [15:0] DATA_DATAOUT_R;
	wire ZERO_DETECTED_R;

	//SIPO_L SIGNALS
	wire SIPO_CLEAR_L;
	wire SIPO_EN_L;
	wire SIPO_DATA_READY_L;

	//SIPO_R SIGNALS
	wire SIPO_CLEAR_R;
	wire SIPO_EN_R;
	wire SIPO_DATA_READY_R;

	wire EN_FIR;

	//Main_Controller Instatiation
	Main_Controller Main_Ctrl (
		.SCLK(SCLK),
		.DCLK(DCLK),
		.RESET_N(RESET_N),
		.START(START),
		.FRAME(FRAME),
		.INREADY(INREADY),
		.OUTREADY(OUTREADY),
		.EN_FIR(EN_FIR),
		.ALU_CLEAR(ALU_CLEAR),
		
		//CONNECTION TO RJ L MEMORY
		.RJ_MEM_CLEAR_L(RJ_CLEAR_L),
		.RJ_WRITE_ADDRESS_L(RJ_WRITE_ADDRESS_L),
		.RJ_WRITE_EN_L(RJ_WRITE_EN_L),

		//CONNECTION TO RJ R MEMORY
		.RJ_MEM_CLEAR_R(RJ_CLEAR_R),
		.RJ_WRITE_ADDRESS_R(RJ_WRITE_ADDRESS_R),
		.RJ_WRITE_EN_R(RJ_WRITE_EN_R),

		//CONNECTION TO COEFFICIENT L MEMORY
		.COEFF_MEM_CLEAR_L(COEFF_CLEAR_L),
		.COEFF_WRITE_ADDRESS_L(COEFF_WRITE_ADDRESS_L),
		.COEFF_WRITE_EN_L(COEFF_WRITE_EN_L),

		//CONNECTION TO COEFFICIENT R MEMORY
		.COEFF_MEM_CLEAR_R(COEFF_CLEAR_R),
		.COEFF_WRITE_ADDRESS_R(COEFF_WRITE_ADDRESS_R),
		.COEFF_WRITE_EN_R(COEFF_WRITE_EN_R),

		//CONNECTION TO DATA L MEMORY
		.DATA_MEM_CLEAR_L(DATA_CLEAR_L),
		.DATA_WRITE_ADDRESS_L(DATA_WRITE_ADDRESS_L),
		.DATA_WRITE_EN_L(DATA_WRITE_EN_L),
		.ZERO_DETECTED_L(ZERO_DETECTED_L),

		//CONNECTION TO DATA R MEMORY
		.DATA_MEM_CLEAR_R(DATA_CLEAR_R),
		.DATA_WRITE_ADDRESS_R(DATA_WRITE_ADDRESS_R),
		.DATA_WRITE_EN_R(DATA_WRITE_EN_R),
		.ZERO_DETECTED_R(ZERO_DETECTED_R),

		//CONNECTION TO SIPO L
		.SIPO_CLEAR_L(SIPO_CLEAR_L),
		.SIPO_EN_L(SIPO_EN_L),
		.SIPO_DATA_READY_L(SIPO_DATA_READY_L),

		//CONNECTION TO SIPO R
		.SIPO_CLEAR_R(SIPO_CLEAR_R),
		.SIPO_EN_R(SIPO_EN_R),
		.SIPO_DATA_READY_R(SIPO_DATA_READY_R)
	);


	RJ_Memory RJ_MEM_L (
		.DCLK(DCLK),
		.SCLK(SCLK),
		.CLEAR(RJ_CLEAR_L),
		.READ_EN(RJ_READ_EN_L),
		.PDATA_IN(PDATA_IN_L),
		.WRITE_ADDRESS(RJ_WRITE_ADDRESS_L),
		.WRITE_EN(RJ_WRITE_EN_L),
		.READ_ADDRESS(RJ_READ_ADDRESS_L),
		.DATAOUT(RJ_DATAOUT_L)
	);

	RJ_Memory RJ_MEM_R (
		.DCLK(DCLK),
		.SCLK(SCLK),
		.CLEAR(RJ_CLEAR_R),
		.READ_EN(RJ_READ_EN_R),
		.PDATA_IN(PDATA_IN_R),
		.WRITE_ADDRESS(RJ_WRITE_ADDRESS_R),
		.WRITE_EN(RJ_WRITE_EN_R),
		.READ_ADDRESS(RJ_READ_ADDRESS_R),
		.DATAOUT(RJ_DATAOUT_R)
	);

	Coefficient_Memory COEFF_MEM_L (
		.DCLK(DCLK),
		.SCLK(SCLK),
		.CLEAR(COEFF_CLEAR_L),
		.READ_EN(COEFF_READ_EN_L),
		.PDATA_IN(PDATA_IN_L),
		.WRITE_ADDRESS(COEFF_WRITE_ADDRESS_L),
		.WRITE_EN(COEFF_WRITE_EN_L),
		.READ_ADDRESS(COEFF_READ_ADDRESS_L),
		.DATAOUT(COEFF_DATAOUT_L)
	);

	Coefficient_Memory COEFF_MEM_R (
		.DCLK(DCLK),
		.SCLK(SCLK),
		.CLEAR(COEFF_CLEAR_R),
		.READ_EN(COEFF_READ_EN_R),
		.PDATA_IN(PDATA_IN_R),
		.WRITE_ADDRESS(COEFF_WRITE_ADDRESS_R),
		.WRITE_EN(COEFF_WRITE_EN_R),
		.READ_ADDRESS(COEFF_READ_ADDRESS_R),
		.DATAOUT(COEFF_DATAOUT_R)
	);

	Data_Memory DATA_MEM_L (
		.DCLK(DCLK),
		.SCLK(SCLK),
		.CLEAR(DATA_CLEAR_L),
		.READ_EN(DATA_READ_EN_L),
		.PDATA_IN(PDATA_IN_L),
		.WRITE_ADDRESS(DATA_WRITE_ADDRESS_L),
		.WRITE_EN(DATA_WRITE_EN_L),
		.READ_ADDRESS(DATA_READ_ADDRESS_L),
		.DATAOUT(DATA_DATAOUT_L),
		.ZERO_DETECTED(ZERO_DETECTED_L)
	);

	Data_Memory DATA_MEM_R (
		.DCLK(DCLK),
		.SCLK(SCLK),
		.CLEAR(DATA_CLEAR_R),
		.READ_EN(DATA_READ_EN_R),
		.PDATA_IN(PDATA_IN_R),
		.WRITE_ADDRESS(DATA_WRITE_ADDRESS_R),
		.WRITE_EN(DATA_WRITE_EN_R),
		.READ_ADDRESS(DATA_READ_ADDRESS_R),
		.DATAOUT(DATA_DATAOUT_R),
		.ZERO_DETECTED(ZERO_DETECTED_R)
	);

	SIPO SIPO_L (
		.CLK(DCLK),
		.CLEAR(SIPO_CLEAR_L),
		.EN(SIPO_EN_L),
		.DATA_IN(INPUTL),
		.PDATA_IN(PDATA_IN_L),
		.FRAME(FRAME),
		.DATA_READY(SIPO_DATA_READY_L)
	);

	SIPO SIPO_R (
		.CLK(DCLK),
		.CLEAR(SIPO_CLEAR_R),
		.EN(SIPO_EN_R),
		.DATA_IN(INPUTR),
		.PDATA_IN(PDATA_IN_R),
		.FRAME(FRAME),
		.DATA_READY(SIPO_DATA_READY_R)
	);

	ALU ALU_MSDAP (
		.SCLK(SCLK),
		.CLEAR(ALU_CLEAR),

		.RJ_DATA_R(RJ_DATAOUT_R),
		.RJ_READ_ADDRESS_R(RJ_READ_ADDRESS_R),
		.RJ_READ_EN_R(RJ_READ_EN_R),

		.RJ_DATA_L(RJ_DATAOUT_L),
		.RJ_READ_ADDRESS_L(RJ_READ_ADDRESS_L),
		.RJ_READ_EN_L(RJ_READ_EN_L),

		.COEFF_DATA_R(COEFF_DATAOUT_R),
		.COEFF_READ_ADDRESS_R(COEFF_READ_ADDRESS_R),
		.COEFF_READ_EN_R(COEFF_READ_EN_R),

		.COEFF_DATA_L(COEFF_DATAOUT_L),
		.COEFF_READ_ADDRESS_L(COEFF_READ_ADDRESS_L),
		.COEFF_READ_EN_L(COEFF_READ_EN_L),

		.DATA_DATA_R(DATA_DATAOUT_R),
		.DATA_READ_ADDRESS_R(DATA_READ_ADDRESS_R),
		.DATA_READ_EN_R(DATA_READ_EN_R),

		.DATA_DATA_L(DATA_DATAOUT_L),
		.DATA_READ_ADDRESS_L(DATA_READ_ADDRESS_L),
		.DATA_READ_EN_L(DATA_READ_EN_L),

		.EN_FIR(EN_FIR),

		.DATAOUT_L(DATAOUT_L),
		.DATAOUT_R(DATAOUT_R)
	);

endmodule
