###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID engnx04a.utdallas.edu)
#  Generated on:      Mon May  5 22:19:55 2025
#  Design:            MSDAP
#  Command:           write_db MSDAP_FINAL
###############################################################
current_design MSDAP
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {Dclk}]  -name Dclk -period 1302000.000000 -waveform {0.000000 651000.000000}
create_clock [get_ports {Sclk}]  -name Sclk -period 33333.300000 -waveform {0.000000 16666.650000}
set_propagated_clock  [get_ports {Dclk}]
set_propagated_clock  [get_ports {Sclk}]
set_load -pin_load -max  1  [get_ports {InReady}]
set_load -pin_load -min  1  [get_ports {InReady}]
set_load -pin_load -max  1  [get_ports {OutReady}]
set_load -pin_load -min  1  [get_ports {OutReady}]
set_load -pin_load -max  1  [get_ports {OutputL}]
set_load -pin_load -min  1  [get_ports {OutputL}]
set_load -pin_load -max  1  [get_ports {OutputR}]
set_load -pin_load -min  1  [get_ports {OutputR}]
set_clock_uncertainty 100 [get_clocks {Sclk}]
set_clock_uncertainty 100 [get_clocks {Dclk}]
set_clock_groups -name __default_1 -asynchronous  -group  [get_clocks {Dclk}]
set_clock_groups -name __default_2 -asynchronous  -group  [get_clocks {Sclk}]
